services:
  server:
    image: genai-server
    build:
      context: backend-python
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    hostname: server
    environment:
      DEBUG: true
      ENFORCE_JWT_AUTH: false
      TASK_RESULT_SCHEMA_PATH: src/task_result_schema.json
      TASK_SCHEMA_PATH: src/task_schema.json
    # TODO: pass self url as command line argument

  node:
    image: genai-node
    build:
      context: client-node
      dockerfile: client-node-comfyui.dockerfile
    depends_on:
      - server

  tests:
    build:
      context: tests
      dockerfile: tests.dockerfile
    environment:
      SERVER_URL: "http://server:8080"
    depends_on:
      - server
      - node
  
  unit_tests:
    image: genai-server
    build:
      context: backend-python
      dockerfile: backend.dockerfile
    entrypoint: ["pytest"]
