services:
  server:
    image: genai-server
    build:
      context: backend-python
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    environment:
      DEBUG: true
      ENFORCE_JWT_AUTH: false
      WS_TASK_TIMEOUT: 10
    # TODO: pass self url as command line argument

  node-comfyui:
    image: genai-node-comfyui
    build:
      context: client-node
      dockerfile: client-node-comfyui.dockerfile
      args:
        COMFYUI_TAG: pytorch-2.2.0-py3.10-cpu-22.04
    command: -b 'ws://server:8080/' -i 'localhost:8188' -t 'comfyUI'
    depends_on:
      - server

  e2e-tests:
    build:
      context: tests
      dockerfile: tests.dockerfile
    environment:
      SERVER_URL: "http://server:8080"
    depends_on:
      - server
      - node-comfyui
    
  server-unit-tests:
    build:
      context: backend-python
      dockerfile: backend.dockerfile
    entrypoint: ["pytest"]

  autopep8:
    build:
      context: backend-python
      dockerfile: utils.dockerfile
    entrypoint: ["autopep8"]
    working_dir: /code
    command: ["--in-place", "--recursive", "/code/src"]
    volumes:
      - ./backend-python/src:/code/src