services:
  server:
    image: genai-server
    build:
      context: backend
    ports:
      - "8080:8080"
    # TODO: pass self url as command line argument
  
  node:
    image: genai-node
    build:
      context: client-node
    depends_on:
      - server

  tests:
    build:
      context: tests
    depends_on:
      - server
      - node
    # TODO: implement one regress test and check that it works with 'docker compsoe up'
