services:
  server:
    image: genai-server
    build:
      context: backend-python
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    hostname: server
    environment:
      DEBUG: true
      ENFORCE_JWT_AUTH: false
    # TODO: pass self url as command line argument

  node:
    image: genai-node
    build:
      context: client-node
      dockerfile: client-node-comfyui.dockerfile
    depends_on:
      - server
    
  server_unit_tests:
    build:
      context: backend-python
      dockerfile: backend.dockerfile
    entrypoint: ["pytest"]

  e2e_tests:
    build:
      context: tests
      dockerfile: tests.dockerfile
    environment:
      SERVER_URL: "http://server:8080"
    depends_on:
      - server
      - node
