# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scaler.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscaler.proto\x12\x0bscaler_grpc\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\"\x82\x01\n\x11\x43reateNodeRequest\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\x13\n\x0bprov_script\x18\x04 \x01(\t\x12\x17\n\nvastai_iid\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\r\n\x0b_vastai_iid\"%\n\x12\x43reateNodeResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"$\n\x11\x44\x65leteNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteNodeResponse\"9\n\x11ListNodesResponse\x12$\n\x05nodes\x18\x01 \x03(\x0b\x32\x15.scaler_grpc.NodeInfo2\xf1\x01\n\x06Scaler\x12O\n\nCreateNode\x12\x1e.scaler_grpc.CreateNodeRequest\x1a\x1f.scaler_grpc.CreateNodeResponse\"\x00\x12O\n\nDeleteNode\x12\x1e.scaler_grpc.DeleteNodeRequest\x1a\x1f.scaler_grpc.DeleteNodeResponse\"\x00\x12\x45\n\tListNodes\x12\x16.google.protobuf.Empty\x1a\x1e.scaler_grpc.ListNodesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scaler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_NODEINFO']._serialized_start = 58
    _globals['_NODEINFO']._serialized_end = 135
    _globals['_CREATENODEREQUEST']._serialized_start = 138
    _globals['_CREATENODEREQUEST']._serialized_end = 268
    _globals['_CREATENODERESPONSE']._serialized_start = 270
    _globals['_CREATENODERESPONSE']._serialized_end = 307
    _globals['_DELETENODEREQUEST']._serialized_start = 309
    _globals['_DELETENODEREQUEST']._serialized_end = 345
    _globals['_DELETENODERESPONSE']._serialized_start = 347
    _globals['_DELETENODERESPONSE']._serialized_end = 367
    _globals['_LISTNODESRESPONSE']._serialized_start = 369
    _globals['_LISTNODESRESPONSE']._serialized_end = 426
    _globals['_SCALER']._serialized_start = 429
    _globals['_SCALER']._serialized_end = 670
# @@protoc_insertion_point(module_scope)
