# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proto.scaler_pb2 as scaler__pb2


class ScalerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNode = channel.unary_unary(
            '/scaler_grpc.Scaler/CreateNode',
            request_serializer=scaler__pb2.CreateNodeRequest.SerializeToString,
            response_deserializer=scaler__pb2.CreateNodeResponse.FromString,
        )
        self.DeleteNode = channel.unary_unary(
            '/scaler_grpc.Scaler/DeleteNode',
            request_serializer=scaler__pb2.DeleteNodeRequest.SerializeToString,
            response_deserializer=scaler__pb2.DeleteNodeResponse.FromString,
        )
        self.ListNodes = channel.unary_unary(
            '/scaler_grpc.Scaler/ListNodes',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=scaler__pb2.ListNodesResponse.FromString,
        )


class ScalerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScalerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateNode': grpc.unary_unary_rpc_method_handler(
            servicer.CreateNode,
            request_deserializer=scaler__pb2.CreateNodeRequest.FromString,
            response_serializer=scaler__pb2.CreateNodeResponse.SerializeToString,
        ),
        'DeleteNode': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteNode,
            request_deserializer=scaler__pb2.DeleteNodeRequest.FromString,
            response_serializer=scaler__pb2.DeleteNodeResponse.SerializeToString,
        ),
        'ListNodes': grpc.unary_unary_rpc_method_handler(
            servicer.ListNodes,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=scaler__pb2.ListNodesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'scaler_grpc.Scaler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Scaler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNode(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scaler_grpc.Scaler/CreateNode',
                                             scaler__pb2.CreateNodeRequest.SerializeToString,
                                             scaler__pb2.CreateNodeResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNode(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scaler_grpc.Scaler/DeleteNode',
                                             scaler__pb2.DeleteNodeRequest.SerializeToString,
                                             scaler__pb2.DeleteNodeResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNodes(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scaler_grpc.Scaler/ListNodes',
                                             google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                                             scaler__pb2.ListNodesResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
