name: Node.js CI

on:
  pull_request:
  push:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.PRIVATE_KEY  }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # next line is only for projects that require builds, like React 
    # - run: CI=false npm run build
    # Deploy
    - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --omit-dir-times --no-perms --archive --compress . root@78.47.190.250:/root/broadcaster-service